// Editais
export const CREATE_EDITAL = "CREATE_EDITAL",
			 READ_EDITAIS = "READ_EDITAIS",
			 UPDATE_EDITAL = "UPDATE_EDITAL",
			 DELETE_EDITAL = "DELETE_EDITAL";

// Usuarios
export const CREATE_USUARIO = "CREATE_USUARIO",
			 READ_USUARIOS = "READ_USUARIOS",
			 UPDATE_USUARIO = "UPDATE_USUARIO",
			 DELETE_USUARIO = "DELETE_USUARIO";